[package]
name = "formats"
edition.workspace = true
version.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Faithful parsers for the binary data formats of TES Travels: Oblivion (Java ME)."

[lints]
workspace = true

[dependencies]

[dev-dependencies]
insta = { version = "1", features = ["yaml"] }
proptest = "1"
