//! Asset loading.
//!
//! The Java code addresses resources by absolute, leading-slash paths
//! (`"/startup.scr"`, `"/l01_1.jtm"`, `"/lang_0.txt"`, ...). We keep those paths
//! verbatim as the canonical key so ported code stays close to the original; the
//! store just maps them onto a directory on disk. A future build can swap this
//! for an `include_bytes!` table generated by `build.rs` without touching
//! callers.

use std::io;
use std::path::{Path, PathBuf};

/// Loads game resources from a directory, keyed by original `/leading-slash`
/// paths.
#[derive(Debug, Clone)]
pub struct AssetStore {
    root: PathBuf,
}

impl AssetStore {
    /// Create a store rooted at `root` (the directory holding the raw assets).
    pub fn new(root: impl Into<PathBuf>) -> Self {
        Self { root: root.into() }
    }

    /// Resolve an original resource path (`"/l01_1.jtm"`) to a filesystem path.
    pub fn resolve(&self, resource: &str) -> PathBuf {
        self.root.join(resource.trim_start_matches('/'))
    }

    /// Load the bytes for a resource addressed by its original path.
    pub fn load(&self, resource: &str) -> io::Result<Vec<u8>> {
        std::fs::read(self.resolve(resource))
    }

    /// List original resource paths with the given extension (no dot), sorted.
    /// e.g. `list("jtm")` -> `["/l01_1.jtm", "/l02_1.jtm", ...]`.
    pub fn list(&self, ext: &str) -> io::Result<Vec<String>> {
        let mut out = Vec::new();
        for entry in std::fs::read_dir(&self.root)? {
            let path = entry?.path();
            if path.extension().and_then(|e| e.to_str()) == Some(ext) {
                if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
                    out.push(format!("/{name}"));
                }
            }
        }
        out.sort();
        Ok(out)
    }

    /// The root directory.
    pub fn root(&self) -> &Path {
        &self.root
    }
}
